# Generated by Django 3.2.10 on 2022-10-26 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField()),
                ('category_name', models.TextField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'group_category',
            },
        ),
    ]
