# Generated by Django 3.2.10 on 2022-11-02 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField()),
                ('sub_category_name', models.CharField(max_length=50)),
                ('sub_category_description', models.TextField(blank=True, max_length=1500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.groupcategorymodel')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
    ]
