# Generated by Django 3.2.10 on 2022-11-09 17:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_subcategorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField()),
                ('product_name', models.CharField(max_length=60)),
                ('price_gross', models.IntegerField()),
                ('price_net', models.IntegerField(blank=True, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategorymodel')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
